| [⬅️ Previous Exercise](Exercise1-5_FunctionsClassesObjects.ipynb) | [🏠 Index](Index.ipynb) | [➡️ Next Exercise](Exercise2-2_Pandas.ipynb) |

# Exercise 2.1: Introduction to Python Data Science using NumPy

Having covered the basics of Python, we will now explore its applications for data science. Bypassing the [hype](https://hbr.org/2012/10/data-scientist-the-sexiest-job-of-the-21st-century), **data science** is an interdisciplinary subject that lies at the intersection of statistics, computer programming, and domain expertise. It is best to think of data science not as a new field of knowledge itself, but rather as a *set of skills* for analysing and interrogating datasets within your existing area of expertise – in our case, environmental science and management.

<img src="./assets/datascience.png" alt="datascience" width="400"/>

Python's extensive, active "ecosystem" of packages like NumPy, Pandas, SciPy, and Matplotlib – all of which we will explore in this next set of exercises – lends itself well to data analysis and scientific computing. In addition, this section outlines techniques for importing, manipulating, visualizing, and exporting data in Python. While data come in a wide variety of formats, it is useful to conceptualize all data as **arrays of numbers** (recall the spreadsheet analogy from Exercise 1.4). For example, an image is, at its core, a two-dimensional array of numbers representing the brightness of each pixel across the image area. When envisioned this way, it is easy to see how the image can be transformed and analysed by manipulating values in the array: 

![imagearray](./assets/imagearray.png)


<p style="height:1pt"> </p>

<div class="boxhead2">
    Exercise 2.1 Topics
</div>

<div class="boxtext2">
<ul class="a">
    <li> 📌 NumPy Arrays </li>
    <ul class="b">
        <li> Constructing arrays from lists </li>
        <li> Constructing arrays from scratch </li>
    </ul>
    <li> 📌 Array Manipulation </li>
    <ul class="b">
        <li> Array attributes </li>
        <li> Indexing + slicing </li>
        <li> Array reduction </li>
        <li> Reshaping, resizing, + rearranging arrays </li>
        <li> Joining + splitting arrays </li>
    </ul>
    <li> 📌 Array Math</li>
    <ul class="b">
        <li> Universal functions </li>
        <li> Array-to-array math: broadcasting </li>
    </ul>
    <li> 📌 Handling missing data </li>
</ul>
</div>


<div class="boxhead2">
    Readings
</div>
<div class="boxtext2">
    This notebook is designed to be run as a stand alone exercise. However, the material covered can be supplemented by <a href="https://proquest-safaribooksonline-com.proxy.library.ucsb.edu:9443/book/programming/python/9781491912126/2dot-introduction-to-numpy/introduction_to_numpy_html"> Chapter 2</a> of the <a href="https://proquest-safaribooksonline-com.proxy.library.ucsb.edu:9443/book/programming/python/9781491912126"> <i>Python Data Science Handbook</i></a>.
</div>

<hr style="border-top: 0.2px solid gray; margin-top: 12pt; margin-bottom: 0pt"></hr>

### Instructions
Work through the exercise, writing code where indicated. To run a cell, click on the cell and press "Shift" + "Enter" or click the "Run" button in the toolbar at the top. Note: Do not restart the kernel and clear all outputs. If this happens, run the last cell in the notebook before proceeding.

<p style="color:#408000; font-weight: bold"> 🐍 &nbsp; &nbsp; This symbol designates an important note about Python structure, syntax, or another quirk.  </p>

<p style="color:#008C96; font-weight: bold"> ▶️ &nbsp; &nbsp; This symbol designates a cell with code to be run.  </p>

<p style="color:#008C96; font-weight: bold"> ✏️ &nbsp; &nbsp; This symbol designates a partially coded cell with an example.  </p>

<p style="color:#008C96; font-weight: bold"> 📚 &nbsp; &nbsp; This symbol designates a practice question.  </p>


<hr style="border-top: 1px solid gray; margin-top: 24px; margin-bottom: 1px"></hr>

## Introduction to NumPy

<img src="./assets/numpy.jpeg" alt="numpy" width="500"/>

NumPy, an abbreviation for *Numerical Python*, is the core library for scientific computing in Python. In addition to manipulation of array-based data, NumPy provides an efficient way to store and operate on very large datasets. In fact, nearly all Python packages for data storage and computation are built on NumPy arrays. 

This exercise will provide an overview of NumPy, including how arrays are created, NumPy functions to operate on arrays, and array math. While most of the basics of the NumPy package will be covered here, there are many, many more operations, functions, and modules. As always, you should consult the [NumPy Docs](https://docs.scipy.org/doc/numpy/reference/index.html) to explore its additional functionality.

Before jumping into NumPy, we should take a brief detour through importing libraries in Python. While most packages we will use – including NumPy – are developed by third-parties, there are a number of "standard" packages that are built into the Python API. The following table contains a description of a few of the most useful modules worth making note of.

| Module | Description | Syntax |
| :----- | :---------- | :----- |
| <a href="https://docs.python.org/3.8/library/os.html" style="text-decoration: none; font-family: Lucida Console, Courier, monospace; font-weight: bold"> os </a> | Provides access to operating system functionality | <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> import os </span> |
| <a href="https://docs.python.org/3.8/library/math.html" style="text-decoration: none; font-family: Lucida Console, Courier, monospace; font-weight: bold"> math </a> | Provides access to basic mathematical functions | <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> import math </span> |
| <a href="https://docs.python.org/3.8/library/random.html" style="text-decoration: none; font-family: Lucida Console, Courier, monospace; font-weight: bold"> random </a> | Implements pseudo-random number generators for various distributions | <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> import random </span> |
| <a href="https://docs.python.org/3.8/library/os.html" style="text-decoration: none; font-family: Lucida Console, Courier, monospace; font-weight: bold"> datetime </a> | Supplies classes for generating and manipulating dates and times | <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> import datetime as dt </span> |

<div class="python">
    🐍 <b>Import syntax.</b> 
    As we saw in Exercise 1.5, modules and packages can be loaded into a script using an <code>import</code> statement: <code>import [module]</code> for the entire module, or <code>from [module] import [identifier]</code> to import a certain class of the module. All modules and packages used in a program should be imported at the beginning of the program.
    
Many packages are imported with standard abbreviations (such as <code>dt</code> for the <code>datetime</code> module) using the following syntax:
    
<p style="margin-left:60pt"><code>import [module] as [name]</code></p>

The standard syntax for importing NumPy is:

<p style="margin-left:60pt"> <code><span style="font-weight:bold; color:#007A00">import</span> numpy <span style="font-weight:bold; color:#007A00">as</span> np</code></p>

</div>

<div class="run">
    ▶️ <b> Run the cell below. </b>
</div>


In [1]:
import numpy as np

### NumPy Arrays
<hr style="border-top: 0.2px solid gray; margin-top: 12px; margin-bottom: 1px"></hr>

The *n*-dimensional array object in NumPy is referred to as an `ndarray`, a multidimensional container of *homogeneous* items – i.e. all values in the array are the same type and size. These arrays can be one-dimensional (one row or column vector), two-dimensional (*m* rows x *n* columns), or three-dimensional (arrays within arrays).

<h4 style="border:1px; border-style:solid; border-color:black; padding: 0.5em;"> <span style="color:black"> Constructing arrays from lists </span> </h4>

There are two main ways to construct NumPy arrays. The first involves using the `np.array()` function to generate an array from one or more lists:

```python
np.array([8,0,9,1,4])
>>> array([8, 0, 9, 1, 4])
```

Recall that unlike lists, all elements within an array must be of the same type. If the types do not match, NumPy will "upcast" if possible (e.g. convert integers to floats):

```python
np.array([8.14,0.12,9,1.77,4])
>>> array([8.14, 0.12, 9.  , 1.77, 4.  ])
```

In these examples, we have created one-dimensional arrays. By default, elements in a one-dimensional array are cast as rows in a column (i.e. a column vector). If, however, we wanted a row vector instead, we could use double brackets `[[]]` to create an array with one row and multiple columns:

```python
np.array([[8,0,9,1,4]]) # row vector with 5 columns
>>> array([[8, 0, 9, 1, 4]])
```

This is because NumPy treats the inner element(s) or list(s) as rows. This is easier to see with a multidimensional array:

```python
np.array([[3,2,0,1],[9,1,8,7],[4,0,1,6]]) # array with 3 rows x 4 columns

>>> array([[3, 2, 0, 1],
           [9, 1, 8, 7],
           [4, 0, 1, 6]])
```


<div class="practice">
    📚  <b> Practice 1. </b> 
    Create the following arrays and assign the corresponding variable names:
<ol class="alpha">
    <li> <code>a</code> </li>
        $ \begin{matrix}
            4 &   5 &   0 & 12 & -1 \\
            8 & -21 &  -4 &  6 &  3 \\
           17 &   1 & -13 &  7 &  0
          \end{matrix}$
    <li> <code>b</code> </li> 
        $ \begin{matrix}
            1.0 & 2.7 & 0 & 0.188 & 4.07 & 0.24
          \end{matrix}$
    <li> <code>c</code> </li> 
        $ \begin{matrix}
            0.4 \\
            0.8 \\
            1.2 \\
            1.6 \\
            2.0 \\
            2.4
          \end{matrix}$
</ol>    
</div>

In [10]:
#basically a matrix
a = np.array([[4,5,0,12,-1],[8, -21, -4, 6, 3], [17,1, -13, 7, 0]])
b = np.array ([[1.0, 2.7, 0, 0.188, 4.07, 0.24]])
c = np.array([ [0.4], [0.8], [1.2], [1.6], [2.0], [2.4]])
print(a)
print(b)
print(c)


[[  4   5   0  12  -1]
 [  8 -21  -4   6   3]
 [ 17   1 -13   7   0]]
[[1.    2.7   0.    0.188 4.07  0.24 ]]
[[0.4]
 [0.8]
 [1.2]
 [1.6]
 [2. ]
 [2.4]]


<h4 style="border:1px; border-style:solid; border-color:black; padding: 0.5em;"> <span style="color:black"> Constructing arrays using functions </span> </h4>

Oftentimes, it will be more efficient to construct arrays from scratch using NumPy functions. The `np.arange()` function is used to generate an array with evenly spaced values within a given interval. `np.arange()` can be used with one, two, or three parameters to specify the *start*, *stop*, and *step* values. If only one value is passed to the function, it will be interpreted as the *stop* value:


```python
# Create an array of the first seven integers 
np.arange(7)
>>> array([0, 1, 2, 3, 4, 5, 6])

# Create an array of floats from 1 to 12
np.arange(1.,13.)
>>> array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

# Create an array of values between 0 and 20, stepping by 2
np.arange(0,20,2)
>>> array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
```

Similarly, the `np.linspace()` function is used to construct an array with evenly spaced numbers over a given interval. However, instead of the *step* parameter, `np.linspace()` takes a *num* parameter to specify the number of samples within the given interval:

```python
# Create an array of 5 evenly spaced values between 0 and 1
np.linspace(0,1,5)
>>> array([0.  , 0.25, 0.5 , 0.75, 1.  ])
```

Note that unlike `np.arange()`, `np.linspace()` includes the *stop* value by default (this can be changed by passing *`endpoint=True`*). Finally, it should be noted that while we could have used `np.arange()` to generate the same array in the above example, it is recommended to use `np.linspace()` when a non-integer step (e.g. 0.25) is desired.



<div class="practice">
    📚  <b> Practice 2. </b> 
<ol class="alpha">
    <li> Create a new array <code>d</code> of integers the multiples of 3 between 0 and 100.</li>
    <li> Create an array <code>f</code> 10 evenly spaced elements between 0 and 2.</li> 
    <li> Re-create array <code>c</code> from Practice 1c using a function. Assign this to variable name <code>g</code>. </li>
</ol>    
</div>

In [21]:
d = np.arange(0, 100, 3)

f = np.linspace(0,2,10)

g = np.arange(0.4, 2.5, 0.4)


print(d)
print(g)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
[0.4 0.8 1.2 1.6 2.  2.4]


There are several functions that take a *shape* argument to generate single-value arrays with specified dimensions passed as a tuple (*rows,columns*):

```python
# Create a 1D array of zeros of length 4
np.zeros(4)
>>> array([0., 0., 0., 0.]

# Create a 4 x 3 array filled with zeros
np.zeros((4,3))
>>> array([[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]])

# Create a 4 x 3 array filled with ones
np.ones((4,3))
>>> array([[1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.],
           [1., 1., 1.]])


# Create a 4 x 3 array filled with 3.14
np.full((4,3),9.87)
>>> array([[9.87, 9.87, 9.87],
           [9.87, 9.87, 9.87],
           [9.87, 9.87, 9.87],
           [9.87, 9.87, 9.87]])
```

The `np.random.rand()` function is used to generate *n*-dimensional arrays filled with random numbers between 0 and 1:

```python
# Create a 4 x 3 array of uniformly distributed random values
np.random.rand(4,3)
>>> array([[0.17461878, 0.74586348, 0.9770975 ],
           [0.77861373, 0.28807114, 0.10639001],
           [0.09845499, 0.36038089, 0.58533369],
           [0.30983962, 0.74786381, 0.27765305]])
```

As we will see, the `np.random.rand()` function is very useful for sampling and modeling.

The last array-construction function we will consider (but by no means the last in the [NumPy API](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html)!) is the `np.eye()` function, which is used to generate the two-dimensional identity matrix:

```python
# Create a 4 x 4 identity matrix
np.eye(4)
>>> array([[1., 0., 0., 0.],
           [0., 1., 0., 0.],
           [0., 0., 1., 0.],
           [0., 0., 0., 1.]])
```

Lastly, it's worth noting that nearly all of these functions contain an optional *dtype* parameter, which can be used to specify the data-type of the resulting array (e.g. `np.ones((4,3),dtype=int)` would return a 4 x 3 array of ones as integers, rather than the default floats).

<div class="practice">
    📚  <b> Practice 3. </b> Assign the following to variables:
    <ol class="alpha">
        <li> A 5x3 array of ones. </li>
        <li> A one-dimensional array of 6 zeros. </li> 
        <li> A 7x7 identity array. </li>
        <li> A random 10x10 array. </li>
</ol>
</div>

In [36]:
a = np.ones((5,3))
b = np.zeros((6))
c = np.eye(7)
array = np.random.rand(10,10)
array.round(2)

array([[0.02, 0.8 , 0.94, 0.44, 0.15, 0.09, 0.78, 0.51, 0.42, 0.48],
       [0.02, 0.26, 0.17, 0.48, 0.15, 0.28, 0.47, 0.04, 0.57, 0.49],
       [0.13, 0.33, 0.07, 1.  , 0.92, 0.98, 0.99, 0.01, 0.99, 0.6 ],
       [0.83, 0.08, 0.29, 0.34, 0.02, 0.85, 0.64, 0.34, 0.58, 0.39],
       [0.4 , 0.7 , 0.37, 0.89, 0.65, 0.73, 0.52, 0.39, 0.08, 0.16],
       [0.26, 0.18, 0.31, 0.44, 0.65, 0.39, 0.1 , 0.71, 0.78, 0.48],
       [0.  , 0.72, 0.49, 0.13, 0.11, 0.26, 0.1 , 0.66, 0.61, 0.34],
       [0.03, 0.78, 0.21, 0.01, 0.81, 0.67, 0.09, 0.01, 0.02, 0.66],
       [0.35, 0.89, 0.29, 0.59, 0.78, 0.76, 0.79, 0.87, 0.91, 0.6 ],
       [0.47, 0.16, 0.35, 0.41, 0.31, 0.65, 0.19, 0.25, 0.54, 0.77]])

### Array Manipulation
<hr style="border-top: 0.2px solid gray; margin-top: 12px; margin-bottom: 1px"></hr>

Having established how to construct arrays in NumPy, let's explore some of the attributes of the `ndarray`, including how to manipulate arrays. Nearly all data manipulation in Python involves NumPy array manipulation; many other Python data tools like Pandas (Exercise 2.2) are built on the NumPy array. Thus, while many of the examples below may seem trivial, understanding these operations will be critical to understanding more complex operations and Python data manipulation more broadly.


<h4 style="border:1px; border-style:solid; border-color:black; padding: 0.5em;"> <span style="color:black"> Array attributes </span> </h4>

Array attributes are properties that are intrinsic to the array itself. While there are quite a few attributes of NumPy arrays, the ones we will use most often provide information about the size, shape, and type of the arrays:

| Method | Description |
| :----- | :---------- |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> ndarray.ndim </span> | Number of array dimensions |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> ndarray.shape </span> | Tuple of array dimensions (*rows*, *columns*) |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> ndarray.size </span> | Total number of elements in the array |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> ndarray.dtype </span> | Data-type of array elements |

For example, let's create a random two-dimensional array and explore its attributes using the above methods.

```python
# Initialize array
a = np.random.rand(4,7)

# Determine array dimensions
a.ndim
>>> 2

# Determine array shame
a.shape
>>> (4, 7)

# Determine array size
a.size
>>> 28

# Determine data-type
a.dtype
>>> dtype('float64')

```

<div class="example">
    ✏️ <b> Try it. </b> 
    Construct two array vectors, a column vector and a row vector, from the list <code>[8,0,9,1,4]</code>, as in the first example. Using the <code>ndarray.ndim</code> and <code>ndarray.shape</code> methods, show the difference between constructing an array with single vs. double brackets.
</div>

In [62]:
arraya = np.array([8,0,9,1,4])
#has no columns

arrayb = np.array([[8,0,9,1,4]])
arrayc = np.array([[8],[0],[9],[1],[4]])

print(arraya.ndim)
print(arrayb.ndim)
print(arraya.shape) # one row five columns
print(arrayb.shape) #five columns all in one row 
print(arraya)
print(arrayc.shape)

1
2
(5,)
(1, 5)
[8 0 9 1 4]
(5, 1)


<div class="practice">
    📚  <b> Practice 4. </b> Use array methods and the array you created in Practice 2a (<code>d</code>) to count the number of multiples of 3 between 0 and 100.
</div>

In [49]:
d = np.arange(0, 100, 3)
d.size #number of numbers

34

<h4 style="border:1px; border-style:solid; border-color:black; padding: 0.5em;"> <span style="color:black"> Indexing + slicing </span> </h4>

Indexing arrays is analogous to indexing lists:

```python
# Initialize a one-dimensional array
x1 = np.array([8,0,9,1,4])

# Return the value in position 1
x1[1]
>>> 0
```

With multidimensional arrays, a tuple of indices can be passed to access the rows and columns of an array: `ndarray[row,column]`. If a single index is passed, the corresponding row element will be returned:

```python
# Initialize a two-dimensional array
x2 = np.array([[3,2,0,1],
               [9,1,8,7],
               [4,0,1,6]])

# Return the value of the element in the 2nd row, 3rd column
x2[1,2]
>>> 8 

# Return the entire second row
x2[1]
>>> array([9, 1, 8, 7])
```

Slicing of arrays allows you to access parts of arrays or *subarrays*. Just like with lists, slicing follows the syntax `ndarray[start:stop:step]`.

```python
# Return the elements in positions 1-4
x1[1:]
>>> array([0, 9, 1, 4])
```

For multidimensional arrays, a tuple of slices is used: `ndarray[row_start:row_end:row_step, col_start:col_end:col_step]`.
    
```python
# Return the entire third column
x2[:,2]
>>> array([0, 8, 1])

# Return the first two rows and two columns
x2[:2,:2]
>>> array([[3, 2],
           [9, 1]])

# Return all rows and every other column
x2[:,::2]
>>> array([[3, 0],
           [9, 8],
           [4, 1]])
```

<div class="practice">
    📚  <b> Practice 5. </b> Using the array you created in Practice 3d,
    <ol class="alpha">
        <li> Print all the elements in column 4. </li>
        <li> Print all the elements in row 7. </li>
        <li> Extract the 4x4 subarray at the center of the array and assign it as a new variable. </li>
        <li> Print the last two values in column 10. </li>
</ol>
</div>

In [74]:
array = np.random.rand(10,10)
print(array)
print(array[:,3])
print(array[6,:])
new = array[4:7,4:7]
print(array[-2,9])


[[0.1604566  0.44440635 0.64707794 0.80392091 0.44477555 0.58110772
  0.24295902 0.3095874  0.59096512 0.90401697]
 [0.33682008 0.82563812 0.50898776 0.90381611 0.92130964 0.90079688
  0.90581969 0.11277108 0.76040366 0.66151555]
 [0.83673194 0.98359799 0.14708832 0.36754389 0.64615854 0.18983448
  0.65139776 0.52591103 0.64551694 0.44818806]
 [0.3750281  0.45297021 0.15861508 0.2180374  0.99813089 0.11904175
  0.0345039  0.43227376 0.33393061 0.18203481]
 [0.91627303 0.35713785 0.75948734 0.92396535 0.48431597 0.75690352
  0.72389011 0.52236783 0.99936069 0.66528052]
 [0.45153171 0.22767428 0.98188426 0.58132842 0.22333702 0.69512821
  0.89348591 0.84925364 0.90355596 0.12535858]
 [0.07795009 0.7069643  0.61256777 0.35914148 0.97750884 0.88769634
  0.91050625 0.24298829 0.1116038  0.03308059]
 [0.07713354 0.2715145  0.16989785 0.1715654  0.71836163 0.28624219
  0.50610253 0.20092506 0.05434785 0.39871907]
 [0.03130085 0.35569127 0.50271944 0.43868537 0.54256646 0.22456275
  0.05329735

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

<div class="practice">
    📚  <b> Practice 6. </b> Create a blank 8x8 matrix and fill it with a checkerboard pattern of 0s and 1s using indexing.
</div>

In [132]:
b = np.zeros((8,8))
b[::2, ::2] = 1
b[1::2, 1::2] = 1
print(b)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


<h4 style="border:1px; border-style:solid; border-color:black; padding: 0.5em;"> <span style="color:black"> Array reduction </span> </h4>

**Array reduction** refers to the computation of summary statistics on an array – i.e. *reducing* an array to a single aggregate value, such as the mean, minimum, maximum, etc. These array reduction methods are similar to those used for lists:

```python
x2 = np.array([[3,2,0,1],
               [9,1,8,7],
               [4,0,1,6]])

# Sum of all values in array
x2.sum()
>>> 42

# Maximum value of the array
x2.max()
>>> 9

# Minimum value of the array
x2.min()
>>> 0

# Mean value of the array
x2.mean()
>>> 3.5

# Standard deviation of the array
x2.std()
>>> 3.095695936834452

```

All of these methods can be passed with an *`axis`* argument, which allows for aggregation across the rows or columns of the array. In NumPy – as well as the many libraries built on NumPy, axis `0` always refers to the *rows* of an array, while axis `1` refers to the *columns*:

```python
# Mean of each row (calculated across columns)
x2.mean(axis=1)
>>> array([1.5 , 6.25, 2.75])

# Maximum value of each column (calculated across rows)
x2.max(axis=0)
>>> array([9, 2, 8, 7])
```

<div class="python">
    🐍 <b>Functions vs. Methods.</b> 
    Recall from Exercise 1.5 that <i>functions</i> and <i>methods</i> in Python are essentially the same thing. The key difference, however, is that functions can be called generically, while methods are always attached to and called on objects. It is also worth noting that while a method may alter the object itself, a function <i>usually</i> simply operates on an object without changing it, and then prints something or returns a value.
    
For each of the array reduction <i>methods</i> demonstrated above, there is a corresponding <i>function</i>. For example, the mean of an array can be calculated using the <i>method</i> <code>ndarray.mean()</code> or the <i>function</i> <code>np.mean(ndarray)</code>.
    
These – and the many additional – aggregation <i>functions</i> in NumPy can be used, not only on arrays, but on any numerical object.
</div>

<h4 style="border:1px; border-style:solid; border-color:black; padding: 0.5em;"> <span style="color:black"> Reshaping, resizing, + rearranging arrays </span> </h4>

Other useful array operations include **reshaping**, **resizing**, and **rearranging** arrays. The `ndarray.reshape()` method is used to change the shape of an array: 

```python
# Initialize a one-dimensional array with 16 elements
a = np.arange(1.0,17.0)

a
>>> array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.])

# Reshape array a into a 4x4 array
b = a.reshape(4,4)

b
>>> [[ 1.  2.  3.  4.]
     [ 5.  6.  7.  8.]
     [ 9. 10. 11. 12.]
     [13. 14. 15. 16.]]


```

There are a few important things to note about the `ndarray.reshape()` method. First and unsurprisingly, the *size* of array must be preserved (i.e. the size of the reshaped array must match that of the original array). Secondly, and perhaps more importantly, the `ndarray.reshape()` method creates a **view** of the original array `a`, rather than a **copy**, which would allow the two variables to exist independently. Because `b` is a *view* of `a`, any changes made to `b` will also be applied to `a`:

```python
# Reset the value in the third row, third column (11.0)
b[2,2] = 0.0

b
>>> array([[ 1.,  2.,  3.,  4.],
           [ 5.,  6.,  7.,  8.],
           [ 9., 10.,  0., 12.],
           [13., 14., 15., 16.]])

a
>>> array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  0., 12., 13., 
           14., 15., 16.])

```

Unlike `ndarray.reshape()`, the `ndarray.resize()` method operates *in-place* on the original array. The `ndarray.resize()` method is used to add or delete rows and/or columns:

```python
# Initialize a 2 x 3 array
a = np.array([[1,2,3],[4,5,6]])

# Copy the original array
smaller = a.copy()
# Use ndarray.resize() to reshape to a 2x2 array and delete the last two elements
smaller.resize(2,2)

smaller
>>> array([[1, 2],
           [3, 4]])

# Copy the original array
bigger = a.copy()
# Use ndarray.resize() to reshape to a 6x6 array by adding zeros
bigger.resize(6,6)

bigger
>>> array([[1, 2, 3, 4, 5, 6],
           [0, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0]])
```


<div class="python">
    🐍 <b>Copies vs. Views</b> 
    This is just one example of many occasions when it is advisable to create a <b>copy</b> of the original object before manipulating it. Had we not copied <code>a</code> before resizing it to a 2x2 array, the last two elements would have been permanently deleted, as <code>a</code> itself would have been resized. A good rule of thumb is to <b>always create a copy</b> before changing or deleting any data.
</div>

Often it is useful to **rearrange** the elements in an array. The `ndarray.transpose()` method – or simply `ndarray.T`, transposes the array, switching the rows and columns, while the `np.flip()`, `np.flipud()`, and `np.fliplr()` functions reverse the order of elements in the array along a given axis:

```python
# Initialize a new 4x5 array
x = np.array([[4, 2, 0, 1, 5],
              [9, 4, 1, 3, 0],
              [6, 0, 8, 5, 9],
              [7, 3, 2, 7, 4]])

# Transpose rows + columns
x.T
>>> array([[4, 9, 6, 7],
           [2, 4, 0, 3],
           [0, 1, 8, 2],
           [1, 3, 5, 7],
           [5, 0, 9, 4]])

# Flip the array (reverse the order of all elements)
np.flip(x)
>>> array([[4, 7, 2, 3, 7],
           [9, 5, 8, 0, 6],
           [0, 3, 1, 4, 9],
           [5, 1, 0, 2, 4]])

# Flip the array up/down (reverse the order of the rows)
np.flipud(x)
>>> array([[7, 3, 2, 7, 4],
           [6, 0, 8, 5, 9],
           [9, 4, 1, 3, 0],
           [4, 2, 0, 1, 5]])

# Flip the array left/right (reverse the order of the columns)
np.fliplr(x)
>>> array([[5, 1, 0, 2, 4],
           [0, 3, 1, 4, 9],
           [9, 5, 8, 0, 6],
           [4, 7, 2, 3, 7]])
```

When passed with the *`axis`* argument, `np.flip()` mimics the `np.flipud()` and `np.fliplr()` functions:

```python
# Flip the array over the row axis (same as np.flipud(x))
np.flip(x, axis=0)
>>> array([[7, 3, 2, 7, 4],
           [6, 0, 8, 5, 9],
           [9, 4, 1, 3, 0],
           [4, 2, 0, 1, 5]])

# Flip the array over the column axis (same as np.fliplr(x))
np.flip(x, axis=1)
>>> array([[5, 1, 0, 2, 4],
           [0, 3, 1, 4, 9],
           [9, 5, 8, 0, 6],
           [4, 7, 2, 3, 7]])
```

<div class="practice">
    📚  <b> Practice 7. </b>
    <ol class="alpha">
        <li> Create a 3x3 matrix with values ranging from 0 to 8. </li>
        <li> Reverse the order of elements in your random 10x10 array from 3d. </li>
</ol>
</div>

In [172]:
d = np.arange(0,9).reshape(3,3)
a = np.random.rand(10,10)
new = a.transpose
print(a)
print(new)
#a.T
x = np.array([[4, 2, 0, 1, 5],
              [9, 4, 1, 3, 0],
              [6, 0, 8, 5, 9],
              [7, 3, 2, 7, 4]])
#print(x)
a = np.flip(x)
#print(a)

[[0.86665747 0.24471909 0.60387445 0.16320828 0.07671388 0.18674871
  0.22199151 0.5406367  0.03641289 0.26669273]
 [0.23978211 0.01020045 0.67561853 0.02435357 0.59589188 0.89893321
  0.84325924 0.0065567  0.28833028 0.85178123]
 [0.8069443  0.18734188 0.31067744 0.88464951 0.41445917 0.3552426
  0.54384426 0.62264071 0.86913469 0.35364113]
 [0.29973523 0.19031833 0.4620922  0.85480542 0.89082024 0.45433429
  0.44210251 0.03771668 0.57549746 0.2582478 ]
 [0.78486892 0.69209066 0.3201208  0.10557396 0.50687262 0.47841425
  0.24473898 0.15631268 0.19408305 0.57110052]
 [0.00356811 0.87208217 0.38146232 0.0703449  0.13606163 0.30746835
  0.57001161 0.04258311 0.97000493 0.73688169]
 [0.21411321 0.85076343 0.57774983 0.20151456 0.89550449 0.0400668
  0.96607835 0.44301142 0.99757034 0.90272938]
 [0.92193128 0.69820401 0.4119126  0.54898995 0.48395325 0.94920589
  0.04351634 0.98847018 0.66582233 0.90434088]
 [0.37133299 0.83139831 0.34430061 0.33546329 0.90053306 0.997341
  0.55173831 0.6

<h4 style="border:1px; border-style:solid; border-color:black; padding: 0.5em;"> <span style="color:black"> Joining + splitting arrays </span> </h4>

So far, we have considered array manipulation routines that operatee on a single array. We will encounter many scenarios in which it is necessary to combine multiple arrays into one or, conversely, to split a single array into two or more separate objects.

**Concatenation** in computer programming refers to the process of joining multiple objects end-to-end. The most common way of concatenating arrays in NumPy is with the `np.concatenate()` function, which takes a tuple of arrays:

```python
# Initialize a 3x3 array
x = np.array([[4,2,0],
              [9,4,1],
              [6,0,8]])
# Initialize a 1x3 array
y = np.array([[2,8,6]])

# Concatenate x and y
np.concatenate((x,y))
>>> array([[4, 2, 0],
           [9, 4, 1],
           [6, 0, 8],
           [2, 8, 6]])
```

Note that, by default, `np.concatenate()` operates along the *row* axis (`0`). To concatenate along the column axis, we must specify `axis=1` as an argument:

```python
# Concatenate x and y along the column axis
np.concatenate((x,y), axis=1)
>>> ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-65-6c2205ef28d2> in <module>
          5 y = np.array([[2,8,6,0]])
          6 
    ----> 7 np.concatenate((x,y),axis=1)

    <__array_function__ internals> in concatenate(*args, **kwargs)

    ValueError: all the input array dimensions for the concatenation axis must match exactly, but along 
    dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1
```

Uh-oh! Unsurprisingly, when we tried to concatenate an array with 1 row to an array with 3 rows, we got a `ValueError`. For `np.concatenate()` to work, the dimensions must match. Thus, we must first transpose `y` before adding it to `x` as a column:

```python
# Transpose y and concatenate x and y along the column axis
np.concatenate((x,y.T),axis=1)
>>> array([[4, 2, 0, 2],
           [9, 4, 1, 8],
           [6, 0, 8, 6]])
```

Equivalently, we could use the `np.vstack()` or `np.hstack()` function to concatenate directly along the row or column axis, respectively:

```python 
# Stack rows of x and y (same as np.concatenate((x,y), axis=0)
np.vstack((x,y))
>>> array([[4, 2, 0],
           [9, 4, 1],
           [6, 0, 8],
           [2, 8, 6]])

# Stack columns of x and y (same as np.concatenate((x,y), axis=1)
np.hstack((x,y.T))
>>> array([[4, 2, 0, 2],
           [9, 4, 1, 8],
           [6, 0, 8, 6]])
```
<div class="practice">
    📚  <b> Practice 8. </b> Create two random 1-D arrays of length 10. Merge them into a 2x10 array and then a 10x2 array.
</div>

In [201]:
a = np.random.rand(1,10)
b = np.random.rand(1,10)
z = np.concatenate((a.T,b.T), axis = 1) #stack by columns 
print(z)

[[0.94108209 0.51624739]
 [0.72480829 0.41548181]
 [0.17033489 0.88305602]
 [0.12649838 0.99193849]
 [0.58272554 0.26991848]
 [0.2176331  0.50640584]
 [0.9241899  0.08663242]
 [0.74660999 0.13421132]
 [0.52039631 0.07540994]
 [0.56519751 0.61411683]]


Conversely, **splitting** allows you to breakdown a single array into multiple arrays. Splitting is implemented with the `np.split()`, `np.vsplit()`, and `np.hsplit()` functions. 

```python
# Initialize a 4x3 array
z = np.array([[4, 2, 0],
              [9, 4, 1],
              [6, 0, 8],
              [2, 8, 6]])

# Split z into two arrays at row 1
np.split(z,[1])
>>> [array([[4, 2, 0]]), array([[9, 4, 1],
                                [6, 0, 8],
                                [2, 8, 6]])]

# OR
np.vsplit(z,[1])
>>> [array([[4, 2, 0]]), array([[9, 4, 1],
                                [6, 0, 8],
                                [2, 8, 6]])]

# Split z into two arrays at column 1
np.hsplit(z,[1])
>>> [array([[4],
            [9],
            [6],
            [2]]), 
     array([[2, 0],
            [4, 1],
            [0, 8],
            [8, 6]])]

```

Multiple indices can be passed to the `np.split()` and related functions, with *n* indices (split points) resulting in *n + 1* subarrays.

<div class="practice">
    📚  <b> Practice 9. </b>
    <ol class="alpha">
        <li> Split your random 10x10 array from 3d into two 10x5 arrays. </li>
        <li> Combine the first 10x5 array from (a), the 10x2 array from 8b, and the other 10x5 array from (a). In other words, recombine the 10x10 array from 3d with two new columns in index positions 5 and 6. Your final array should have 10 rows and 12 columns. Verify this by printing the shape of the resulting array. </li>
</ol>
</div>

In [198]:
random_array = np.random.rand(10,10)
[a,b] = np.hsplit(random_array,[5])
print(a,"\n\n\n",b) 

first = np.ones([10,5])
second = np.ones([10,2])*2
third = np.ones ([10, 5])*3
#first concatenate the first and second array
np.concatenate((first, second, third), axis =1)
#add by column


[[0.84634951 0.62773414 0.49670534 0.29444404 0.37021606]
 [0.78316158 0.28396221 0.96604163 0.80808032 0.77998064]
 [0.633737   0.06370582 0.24365693 0.97852484 0.93330778]
 [0.51790518 0.80955945 0.42647303 0.24836238 0.9695093 ]
 [0.39845662 0.49692812 0.42847741 0.62415923 0.86651618]
 [0.80257949 0.4912853  0.05903816 0.86989852 0.65682851]
 [0.34605571 0.52130776 0.6360314  0.37837437 0.03156772]
 [0.03891444 0.61320282 0.46484078 0.45960086 0.95020881]
 [0.16009492 0.58918999 0.38664665 0.08968531 0.84381691]
 [0.67773601 0.43159918 0.16600621 0.117692   0.67615119]] 


 [[0.35428358 0.07305408 0.48866781 0.35407738 0.83444573]
 [0.49523269 0.4925288  0.0370078  0.65779461 0.52335684]
 [0.7218856  0.6037344  0.96961242 0.7501721  0.56994351]
 [0.68913943 0.81696224 0.12698755 0.30035782 0.5671503 ]
 [0.01818658 0.39079839 0.09554686 0.43589867 0.25025439]
 [0.58177947 0.80269493 0.70760638 0.58467732 0.54363709]
 [0.65711135 0.42624247 0.7030329  0.73154719 0.47734072]
 [0.64612

array([[1., 1., 1., 1., 1., 2., 2., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 2., 2., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 2., 2., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 2., 2., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 2., 2., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 2., 2., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 2., 2., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 2., 2., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 2., 2., 3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1., 2., 2., 3., 3., 3., 3., 3.]])

### Array Math

<hr style="border-top: 0.2px solid gray; margin-top: 12px; margin-bottom: 1px"></hr>

One of the key advantages of NumPy is its ability to perform *vectorized* operations using **universal functions** (ufuncs), which perform element-wise operations on arrays very quickly. For example, say we had a very large list of data, and we wanted to perform some mathematical operation on all of the data elements. We could store this data as a `list` or an `ndarray`:

```python
# Create a list of the first 10,000 integers
a = list(range(10000))

# Create a one-dimensional array of the first 10,000 integers
b = np.arange(10000)
```

Now, let's multiply each element in our dataset by 2. We can accomplish this by using a `for` loop for the list `a` and a **ufunc** for array `b`. (The `%timeit` module is a built-in Python function used to calculate the time it takes to execute short code snippets.)

```python
# Use a for loop to multiply every element in a by 2
%timeit [i*2 for i in a]
# Use a ufunc to multiply every element in b by 2
%timeit b * 2

>>> 388 µs ± 30.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
    3.58 µs ± 41.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```


The `%timeit` module is a built-in Python function used to calculate the time it takes to execute short code snippets.

<div class="run">
    ▶️ <b> Run the cell below. </b>
</div>

In [203]:
#comparison of speed of the two methods
#first method takes more time
# Create a list of the first 10,000 integers
list10 = list(range(10000))
# Use a for loop to multiply every element in a by 2
%timeit [i*2 for i in a]

# Create a one-dimensional array of the first 10,000 integers
array10 = np.arange(10000) #makes a numpy array
# Use a ufunc to multiply every element in b by 2
%timeit array10 * 2

2.68 µs ± 19.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
4.66 µs ± 28.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


As you can see, the `for` loop took about 100 times longer than the exact same element-wise array operation!

<h4 style="border:1px; border-style:solid; border-color:black; padding: 0.5em;"> <span style="color:black"> Computation on single arrays using ufuncs </span> </h4>

Ufuncs are fairly straightforward to use, as they rely on Python's native operators (e.g. `+`, `-`, `*`, `/`):

```python
# Create a 2x4 array of floats
x  = np.array([[1.,2.,3.,4.],
               [5.,6.,7.,8.]])

# Do some math
# Addition
x + 12
>>> array([[13., 14., 15., 16.],
           [17., 18., 19., 20.]])

# Subtraction
x - 400
>>> array([[-399., -398., -397., -396.],
           [-395., -394., -393., -392.]])

# Exponentiation
x ** 2
>>> array([[ 1.,  4.,  9., 16.],
           [25., 36., 49., 64.]])

# Combine operations
10 ** (x/2)
>>> array([[3.16227766e+00, 1.00000000e+01, 3.16227766e+01, 1.00000000e+02],
           [3.16227766e+02, 1.00000000e+03, 3.16227766e+03, 1.00000000e+04]])
```

These arithmetic operators act as *wrappers* (effectively shortcuts) around specific built-in NumPy functions; for example, the `+` operator is a convenient shortcut for the `np.add()` function:

```python
x + 2
>>> array([[ 3.,  4.,  5.,  6.],
           [ 7.,  8.,  9., 10.]])

np.add(x,2)
>>> array([[ 3.,  4.,  5.,  6.],
           [ 7.,  8.,  9., 10.]])
```

The following table contains a list of arithmetic operators implemented by NumPy. Note that these functions work on *all* numerical objects, not just arrays.

<p style="height:12pt"> </p>

<center> <b>Arithmetic functions in NumPy </b> </center>

| Operator | ufunc | Description |
| :------- | :---- | :---------- |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> +</span> | <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.add() </span> | Addition |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> -</span> | <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.subtract() </span> | Subtraction |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> * </span> | <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.multiply() </span> | Multiplication |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> / </span> | <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.divide() </span> | Division |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> // </span> | <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.floor_divide() </span> | Floor division (returns largest integer) |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> ** </span> | <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.power() </span> | Exponentiation |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> % </span> | <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.mod() </span> | Modulus/remainder |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> \*\*(1/2) </span> | <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.sqrt() </span> | Square root-alize |


Furthermore, as a *numerical* package, NumPy implements many additional mathematical operations for use in Python – on arrays or otherwise. The following tables show some of the more commonly used mathematical functions in NumPy. The `x` is used to denote a numerical object – this could be an `int`, `float`, `list`, `ndarray`, etc.

<p style="height:12pt"> </p>

<center> <b>Logarithmic functions </b> </center>

| ufunc | Operation |
| :---- | :---------- |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.exp(x) </span> | $e^x$ |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.log(x) </span> | $\ln x$|
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.log10(x) </span> | $\log x$ |


<p style="height:12pt"> </p>

<center> <b> Trigonometric functions </b> </center>

| ufunc | Description |
| :---- | :---------- |
|<span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.sin(x) </span>|$\sin{x}$|
|<span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.cos(x) </span>|$\cos{x}$|
|<span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.tan(x) </span>|$\tan{x}$|
|<span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.arcsin(x) </span>| $\sin^{-1}{x}$
|<span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.arccos(x) </span>| $\cos^{-1}{x}$|
|<span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.arctan(x) </span>| $\tan^{-1}{x}$|

<p style="height:12pt"> </p>

Note: NumPy assumes all inputs to trigonometic functions are in units of *radians*. The `np.radians()` function can be used to convert from degrees to radians, while the `np.degrees()` function does the opposite.

<p style="height:12pt"> </p>
<center> <b> Useful mathematical constants </b> </center>

| Constants | Description |
| :-------- | :---------- |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.e </span> | $e$ |
| <span style="font-family: Lucida Console, Courier, monospace; font-weight: bold"> np.pi </span> | $\pi$ |



<h4 style="border:1px; border-style:solid; border-color:black; padding: 0.5em;"> <span style="color:black"> Array-to-array math </span> </h4>

So far, we have only considered operations between a single array and an integer, but often it is necessary to perform mathematical operations on multiple arrays. Much like NumPy handles single array operations, array-to-array math in NumPy uses ufuncs to perform element-wise calculations. For arrays of the same dimensions, this is straight forward:

```python
x  = np.array([[1.,2.,3.,4.],
               [5.,6.,7.,8.]])

y = np.array([[9.,87.,3.,5.6],
              [-1.,4.,7.1,8.]])

# Addition
x + y
>>> array([[10. , 89. ,  6. ,  9.6],
           [ 4. , 10. , 14.1, 16. ]])

# Division
x / y
>>> array([[ 0.11111111,  0.02298851,  1.        ,  0.71428571],
           [-5.        ,  1.5       ,  0.98591549,  1.        ]])
```

For arrays whose dimensions do not match, NumPy does something called **broadcasting**. So long as one dimension of each array matches and one array has a dimension of 1 in one direction, the smaller array is "broadcast" to the dimensions of the larger array. In this process, the row or column is replicated to match the dimensions of the larger array. This is best illustrated in the following diagram:

<img src="./assets/broadcasting.png" alt="broadcasting" width="600"/>


```python
a = np.array([[1.,2.,3.,4.],
             [5.,6.,7.,8.]])

b = np.array([10,11,12,13])

c = np.array([[1.],
             [20.]])

# Row-wise
a + b
>>> array([[11., 13., 15., 17.],
           [15., 17., 19., 21.]])

# Column-wise
a + c
>>> array([[ 2.,  3.,  4.,  5.],
           [25., 26., 27., 28.]])

# Multiple operations
a + c**2
>>> array([[  2.,   3.,   4.,   5.],
           [405., 406., 407., 408.]])

```

<div class="practice">
    📚  <b> Practice 10. </b>
    <ol class="alpha">
        <li> Raise array <code>b</code> to the power of array <code>c</code>. </li>
        <li> Create a new 5x10 array of random values. Subtract the mean of each row from every value. </li>
</ol>
</div>

In [229]:
a = np.array([[1.,2.,3.,4.],
             [5.,6.,7.,8.]])

b = np.array([10,11,12,13])

c = np.array([[1.],
             [20.]])
b**c
z = np.random.rand(10,5)
row_means = np.mean(z, axis = 1) #get the mean of each row 

b = np.array([row_means])
z - b.T


array([[-0.13986838,  0.10048576,  0.22100793,  0.00921197, -0.19083727],
       [ 0.16603247, -0.14853975, -0.0260876 , -0.09770448,  0.10629935],
       [ 0.26126455,  0.12888827,  0.13014856, -0.43417043, -0.08613094],
       [ 0.16229158, -0.34479389,  0.15699337,  0.460862  , -0.43535306],
       [-0.06630905, -0.25333275, -0.05113548,  0.52446033, -0.15368304],
       [-0.04860627,  0.30953537,  0.37759093, -0.45604461, -0.18247543],
       [ 0.44494599, -0.17124375, -0.02600144, -0.13606847, -0.11163234],
       [ 0.33195923, -0.3564837 ,  0.22860452, -0.31427601,  0.11019597],
       [-0.19597117, -0.13962641,  0.09070634,  0.05215356,  0.19273769],
       [ 0.44554715, -0.30525432,  0.04323066, -0.26488827,  0.08136478]])

### Missing Data
<hr style="border-top: 0.2px solid gray; margin-top: 12px; margin-bottom: 1px"></hr>

Most real-world datasets – environmental or otherwise – have data gaps. Data can be missing for any number of reasons, including observations not being recorded or data corruption. While a cell corresponding to a data gap may just be left blank in a spreadsheet, when imported into Python, there must be some way to handle "blank" or missing values. 

Missing data should not be replaced with zeros, as 0 can be a valid value for many datasets, (e.g. temperature, precipitation, etc.). Instead, the convention is to fill all missing data with the constant **NaN**. NaN stands for "Not a Number" and is implemented in NumPy as `np.nan`.

NaNs are handled differently by different packages. In NumPy, all computations involving NaN values will return `nan`:

```python
data = np.array([[2.,2.7.,1.89.],
                 [1.1, 0.0, np.nan],
                 [3.2, 0.74, 2.1]])

data.mean()
>>> nan
```

In this case, we'd want to use the alternative `np.nanmean()` function, which ignores NaNs:

```python
data.nanmean()
>>> 1.71625
```

NumPy has several other functions – including `np.nanmin()`, `np.nanmax()`, `np.nansum()` – that are analogous to the regular ufuncs covered above, but allow for computation of arrays containing NaN values.



<hr style="border-top: 0.2px solid gray; margin-top: 12pt; margin-bottom: 0pt"></hr>

### Wrapping up

The topics covered in this exercise are but a small window into the wide world of NumPy, but by now you should be familiar with the basic objects and operations in the NumPy library, which are the building blocks of data science in Python. As always – especially now that we've begun exploring third-party packages – refer to the **[NumPy docs](https://numpy.org/doc/1.18/reference/index.html)** for comprehensive information on all functions, methods, routines, etc. and to check out more of NumPy's capabilities. 

Next, we'll explore one of data scientists' favorite libraries: 🐼.


<hr style="border-top: 1px solid gray; margin-top: 24px; margin-bottom: 1px"></hr>

In [ ]:
# IGNORE THIS CELL
from IPython.core.display import HTML
def css_styling():
    styles = open("./styles/exercises.css", "r").read()
    return HTML(styles)
css_styling()